### ISSUE TITLE
Set up Dev enviroment

### ISSUE THREAD

**Issue by Jwhiles** [The-Authenticators/gitpom#1]
what do we want?

- hapi 
- inert 
- eslint
- handlebars
- request
- ramda?!?!?!?!??!?

**Comment by Jwhiles** [comment]
ramda?

**Comment by Jwhiles** [comment]
?!

**Comment by marisid** [comment]
- tape
- vision
- hapi-auth-cookie
- jwt2

**Comment by marisid** [comment]
- env2  as well
