### ISSUE TITLE
make loads of templates

### ISSUE THREAD

**Issue by Jwhiles** [The-Authenticators/gitpom#2]

**Comment by marisid** [comment]
-  [x] Use a layout
-  [x] Create a `home.html` view with a `header`, a `login` and a `repos` partial
-  [x]  Create an `issues.html` view with a `header` partial and an `issues` partial
-  [x] Create a `timer.html` view with a `header` partial, a `time` partial and an `options` partial (TBC)

**Comment by marisid** [comment]
Move header in the layout as it repeats itself everywhere really.

**Comment by marisid** [comment]
Header still left as a partial but all templates completed.
