### ISSUE TITLE
Pomodoro Timer - Front End

### ISSUE THREAD

**Issue by Jwhiles** [The-Authenticators/gitpom#5]
This should be relatively simple, should keep time using date objects, 

when timer is finished should let user send a request back to the server to
- close issue
- abandon issue (unassign and remove label)
- restart time and keep working on issue (Steve - this won't require a request to the server as there won't be any updated state. Unless the server wants to independently time the activity in case the user closes the window, for example?)

To build:

- [x] Handlebars partial for timer
- [x] Client-side script to handle timer
- [x] HTTP request functions to inform server when issues are abandoned/completed
- [x] CSS to style timer

**Comment by marisid** [comment]
Hey Steve! Could you work on the pomodoro timer in the front-end (ideally TDD as you have it from our previous stopwatch project?) and maybe setup a partial for it (refer to issue #2) as well?

**Comment by marisid** [comment]
P.S. We are thinking to put the user options (when the time is off) in a separate partial, so this should be a separate issue really. I'm working on the readme now, so it will all make more sense soon :smile:

**Comment by stevehopkinson** [comment]
So is the idea that the timer partial will be rendered on the server-side, but with update/extra functionality handled on the client-side?

**Comment by marisid** [comment]
Yes, we can link to the `app.js` in the `pomodoro.html` so the functionality for the timer partial will be picked up from the client-side.

**Comment by stevehopkinson** [comment]
Handlebars partial and timer script (with HTTP requests stubbed out) addressed in #16
