### ISSUE TITLE
Login doesn't work first time

### ISSUE THREAD

**Issue by tbtommyb** [The-Authenticators/gitpom#58]
You need to reload the page after you login.

**Comment by Jwhiles** [comment]
this seems to be a problem with the cookie not being set in time. I guess we need an auto redirect/to somehow wait for a second or two

**Comment by tbtommyb** [comment]
See [my comment](https://github.com/Authosaurus/velocity-tracker/issues/36) in response to Marina's issue on our repo. It would be good if you could see if it works for you as I'm not completely sure it solves the issue.
