### ISSUE TITLE
Login Bug

### ISSUE THREAD

**Issue by njsfield** [The-Authenticators/gitpom#59]
This is a general bug with redirecting.

After initially logging in and setting credentials, redirecting to home does not initially carry credentials (you have to click log in again, it's like a delay between your credentials being set).

Solution? Instead of redirecting, reply with a view with message 'Success you've logged in, click to go to your profile', which includes a button to direct you to your desired route. Or additionally add client side javascript that automatically clicks this button

**Comment by marisid** [comment]
Thanks @njsfield!
